AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance creation for R8
Parameters:
  pVPCId:
    Type: String
  pSubnetId:
    Description: Subnet to place the EC2Instance
    Type: String
  pIP:
    Description: Enter IP
    Type: String

  pBastionInstanceType:
    ConstraintDescription: must be a valid EC2 instance type.
    Default: m4.xlarge
    Description: EC2 instance type
    Type: String
  pKeyName:
    Description: Name of an existing EC2 KeyPair to enable access to the instance
    Type: AWS::EC2::KeyPair::KeyName
  pExperianInternalIP:
    Default: 89.174.214.74/32
    Description: CIDR of the Experian's IP
    Type: String
  pLinuxBastionAMI:
    Default: ami-4836a428
    Description: LinuxBastion AMI
    Type: String
  pHostLevelLogGroupName:
    Default: HostLogs
    Description: Name of HostLogs group name
    Type: String
  pAdditionalSG:
    Default: sg-454ba134
    Description: Additional SG to assign
    Type: String
  pBastionInstanceProfile:
    Description: Instance Profile to be assigned to the EC2 instance
    Type: String
  pSquidProxyPort:
    Default: 3128
    Description: Port for proxy
    Type: String
  pSquidProxyHost:
    Default: internal-SquidProx-ElasticL-N5GE9S9HX03T-825324055.us-east-1.elb.amazonaws.com
    Description: host for proxy
    Type: String
Resources:
  rBastionHostSG:
    Properties:
      GroupDescription: Enable SSH/RDP access
      SecurityGroupIngress:
      - CidrIp: !Ref 'pExperianInternalIP'
        FromPort: '22'
        IpProtocol: tcp
        ToPort: '22'
      - CidrIp: !Ref 'pExperianInternalIP'
        FromPort: '3389'
        IpProtocol: tcp
        ToPort: '3389'
      Tags:
      - Key: IAP
        Value: Experian
      - Key: Environment
        Value: Production
      - Key: Name
        Value: sg_bastion_host
      VpcId: !Ref 'pVPCId'
    Type: AWS::EC2::SecurityGroup
#  rBastionEIP:
#    Type: AWS::EC2::EIP
#    Properties:
#      Domain: vpc

  rBastionENI:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !Ref 'pSubnetId'
      Description: Interface for controlling traffic such as SSH
      GroupSet:
      - !Ref rBastionHostSG
      - !Ref pAdditionalSG
      SourceDestCheck: true
#  rBastionEIPAssociation:
#    Type: AWS::EC2::EIPAssociation
#    Properties:
#      AllocationId: !GetAtt rBastionEIP.AllocationId
#      NetworkInterfaceId: !Ref rBastionENI
  rBastionHost:
    Type: AWS::EC2::Instance
    Metadata:
        AWS::CloudFormation::Init:
            config:
#                packages:
#                    yum:
#                        unzip: []
                files:
#                    '/etc/awslogs/awscli.conf':
#                        content: !Sub |
#                            [plugins]
#                            cwlogs = cwlogs
#                            [default]
#                            region = ${AWS::Region}
                     '/etc/systemd/system/amazon-ssm-agent.service':
                        content: !Sub |
                            [Unit]
                            Description=amazon-ssm-agent
                            Wants=network-online.target
                            After=network-online.target

                            [Service]
                            Type=simple
                            Environment="HTTP_PROXY=http://${pSquidProxyHost}:${pSquidProxyPort}"
                            Environment="no_proxy=169.254.169.254"
                            WorkingDirectory=/usr/bin/
                            ExecStart=/usr/bin/amazon-ssm-agent
                            KillMode=process
                            Restart=on-failure
                            RestartSec=15min

                            [Install]
                            WantedBy=network-online.target
                    '/var/awslogs/etc/proxy.conf':
                        content: !Sub |
                            HTTP_PROXY=http://${pSquidProxyHost}:${pSquidProxyPort}
                            HTTPS_PROXY=https://${pSquidProxyHost}:${pSquidProxyPort}
                            NO_PROXY=169.254.169.254
                    '/etc/init.d/awsagent.env':
                        content: !Sub |
                            export http_proxy=http://${pSquidProxyHost}:${pSquidProxyPort}
                            export https_proxy=https://${pSquidProxyHost}:${pSquidProxyPort}
                            export no_proxy=169.254.169.254
                    '/var/awslogs/etc/awslogs.conf':
                        content: !Sub |
                            [general]
                            state_file = /var/awslogs/state/agent-state
                            [/var/log/secure]
                            file = /var/log/secure
                            log_group_name = ${pHostname}
                            log_stream_name = secure-{instance_id}
                            datetime_format = %b %d %H:%M:%S
                            [/var/log/messages]
                            file = /var/log/messages
                            log_group_name = ${pHostLevelLogGroupName}
                            log_stream_name = messages-{instance_id}
                            datetime_format = %b %d %H:%M:%S
                            [/var/log/audit/audit.log]
                            file = /var/log/audit/audit.log
                            log_group_name = ${pHostLevelLogGroupName}
                            log_stream_name = audit-{instance_id}
                            datetime_format = %b %d %H:%M:%S
                            [/var/log/aide/aide.log]
                            file = /var/log/aide/aide.log
                            log_group_name = ${pHostLevelLogGroupName}
                            log_stream_name = aide-{instance_id}
                            datetime_format = %b %d %H:%M:%S
#                    '/tmp/amazon-ssm-agent.rpm':
#                        source: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
                commands:
                    0-startawslogs:
                        command:
                          #curl https://s3.amazonaws.com//aws-cloudwatch/downloads/latest/awslogs-agent-setup.py -O;
                          #python ./awslogs-agent-setup.py --region us-east-1 --non-interactive --configfile=/etc/awslogs/awslogs.conf;
                          service awslogs restart
                    1-restartssmagent:
                        command:
                          systemctl daemon-reload;
                          service amazon-ssm-agent restart
                    2-chkconfigagents:
                        command:
                          chkconfig awslogs on;
                          chkconfig amazon-ssm-agent on;
                          /etc/init.d/awsagent restart
#                    2-installssmagent:
#                        command: yum install -y amazon-ssm-agent.rpm
#                        cwd: /tmp
    Properties:
      IamInstanceProfile: !Ref 'pBastionInstanceProfile'
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          VolumeSize: '200'
      ImageId: !Ref 'pLinuxBastionAMI'
      InstanceType: !Ref 'pBastionInstanceType'
      KeyName: !Ref 'pKeyName'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -x
          crontab -l | sed "/^[^#].*checkhealth/s/^/#/" | crontab -
          # Enable Crontab
          #crontab -l | sed "/^#.*checkhealth/s/^#//" | crontab -
          export http_proxy=http://${pSquidProxyHost}:${pSquidProxyPort}
          export https_proxy=https://${pSquidProxyHost}:${pSquidProxyPort}
          export no_proxy="169.254.169.254, s3.amazonaws.com"
          echo -e "# Generated by NetworkManager\nsearch gdc.local mck.experian.com ec2.internal aln.experian.com acloud.experian.corp\nnameserver 169.254.169.253\nnameserver 10.8.18.167\nnameserver 10.8.9.97" > /etc/resolv.conf
          /opt/aws/bin/cfn-init --stack ${AWS::StackName} --resource rBastionHost --region ${AWS::Region}
          #cfn-hup || error_exit 'Failed to start cfn-hup'
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource rBastionHost
      NetworkInterfaces:
        -
          NetworkInterfaceId: !Ref rBastionENI
          DeviceIndex: 0
      Tags:
      - Key: Environment
        Value: Development
      - Key: Name
        Value: experian_r8_bastion
Outputs:
  oBastionHost:
    Description: Bastion host
    Value: !Ref 'rBastionHost'