#Jerome Chadee
#Creates S3 bucket and retains it if stack is destroyed. Also, if the bucket exist, allows user to create new stack to update the policy.
Description: Stack to create and manage s3 buckets
Parameters:
  MemberAccountNumber:
    Description: AWS Account Number for Member Account
    Type: String
    MaxLength: 12
    MinLength: 12
    AllowedPattern: "[0-9]+"
    Default: '528150397796'
  pCreateS3Bucket:
      Description: Set to false if the bucket already exist
      Default: false
      AllowedValues:
        - false
        - true
      Type: String
  pS3BucketName:
      Description: S3Bucket Name
      Type: String
      Default: 'expn-cis-cicd-pipeline-code-repo'
  pRestrictByVPC:
      Default: false
      Description: VPC to restrict S3 Access to
      AllowedValues:
        - false
        - true
      Type: String
  pVPCId:
      Description: VPC to restrict S3 Access to
      Type: String
Conditions:
  cIsAnewBucket: !Equals [!Ref pCreateS3Bucket, true]
  cRestrictByVPCTrue: !Equals [!Ref pRestrictByVPC, true]
  cRestrictByVPCFalse: !Equals [!Ref pRestrictByVPC, false]
Resources:
  rS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Condition: cIsAnewBucket
    Properties:
      BucketName: !Ref pS3BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enable
  rS3BucketPolicyWithVPC:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Retain
    Condition: cRestrictByVPCTrue
    Properties:
      Bucket: !Ref pS3BucketName
      PolicyDocument:
        Version: '2012-10-17'
        Id: !Sub S3BucketPolicy${pS3BucketName}
        Statement:
        #Restrict by VPC
        - Sid: RestrictToVPC
          Effect: Deny
          Principal: "*"
          Action: s3:*
          Resource: !Sub arn:aws:s3:::${pS3BucketName}/*
          Condition:
            StringNotEquals:
              aws:sourceVpc: !Ref pVPCId
        - Sid: DenyIncorrectEncryptionHeader
          Effect: Deny
          Principal: "*"
          Action: s3:PutObject
          Resource: !Sub arn:aws:s3:::${pS3BucketName}/*
          Condition:
            StringNotEquals:
              s3:x-amz-server-side-encryption: AES256
        - Sid: DenyUnEncryptedObjectUploads
          Effect: Deny
          Principal: "*"
          Action: s3:PutObject
          Resource: !Sub arn:aws:s3:::${pS3BucketName}/*
          Condition:
            'Null':
              s3:x-amz-server-side-encryption: 'true'
        - Sid: DenyNonSSLAccess
          Effect: Deny
          Principal: "*"
          Action: s3:*
          Resource: !Sub arn:aws:s3:::${pS3BucketName}/*
          Condition:
            Bool:
              aws:SecureTransport: 'false'
        - Sid: SecOps
          Effect: Allow
          Principal:
            AWS:
              - arn:aws:iam::647367615943:root
              - arn:aws:iam::902577807644:root
              - arn:aws:iam::581463129500:root
              - arn:aws:iam::227513596010:root
              - arn:aws:iam::989638200024:root
              - arn:aws:iam::227793691312:root
              - arn:aws:iam::227011717743:root
              - arn:aws:iam::041821919363:root
              - arn:aws:iam::639676961119:root
              - arn:aws:iam::938727733271:root
              - arn:aws:iam::796796542496:root
              - arn:aws:iam::215308655391:root
              - arn:aws:iam::720557144887:root
              - arn:aws:iam::859416391807:root
              - arn:aws:iam::512481679155:root
              - arn:aws:iam::339153151760:root
              - arn:aws:iam::020959639949:root
              - arn:aws:iam::902577807644:root
              - arn:aws:iam::068039548225:root
              - arn:aws:iam::002827315474:root
              - arn:aws:iam::188129649881:root
              - arn:aws:iam::035781065801:root
              - arn:aws:iam::060998627520:root
              - arn:aws:iam::121922704398:root
              - arn:aws:iam::590119761358:root
              - arn:aws:iam::756241440375:root
              - arn:aws:iam::831628682309:root
              - arn:aws:iam::873302766205:root
              - arn:aws:iam::319044514607:root
              - arn:aws:iam::387576552623:root
              - arn:aws:iam::944106961327:root
              - arn:aws:iam::091089235314:root
              - arn:aws:iam::726805105719:root
              - arn:aws:iam::978261374777:root
              - arn:aws:iam::872722267528:root
              - arn:aws:iam::003998443196:root
              - arn:aws:iam::649044511533:root
              - arn:aws:iam::994075455914:root
              - arn:aws:iam::858664478982:root
              - arn:aws:iam::980851882997:root
              - arn:aws:iam::438164225206:root
              - arn:aws:iam::303824459716:root
          Action: s3:*
          Resource:
            - !Sub arn:aws:s3:::${pS3BucketName}
            - !Sub arn:aws:s3:::${pS3BucketName}/*

  rS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Retain
    Condition: cRestrictByVPCFalse
    Properties:
      Bucket: !Ref pS3BucketName
      PolicyDocument:
        Version: '2012-10-17'
        Id: !Sub S3BucketPolicy${pS3BucketName}
        Statement:
        - Sid: DenyIncorrectEncryptionHeader
          Effect: Deny
          Principal: "*"
          Action: s3:PutObject
          Resource: !Sub arn:aws:s3:::${pS3BucketName}/*
          Condition:
            StringNotEquals:
              s3:x-amz-server-side-encryption: AES256
        - Sid: DenyUnEncryptedObjectUploads
          Effect: Deny
          Principal: "*"
          Action: s3:PutObject
          Resource: !Sub arn:aws:s3:::${pS3BucketName}/*
          Condition:
            'Null':
              s3:x-amz-server-side-encryption: 'true'
        - Sid: DenyNonSSLAccess
          Effect: Deny
          Principal: "*"
          Action: s3:*
          Resource: !Sub arn:aws:s3:::${pS3BucketName}/*
          Condition:
            Bool:
              aws:SecureTransport: 'false'
        - Sid: SecOps
          Effect: Allow
          Principal:
            AWS:
              - arn:aws:iam::647367615943:root
              - arn:aws:iam::902577807644:root
              - arn:aws:iam::581463129500:root
              - arn:aws:iam::227513596010:root
              - arn:aws:iam::989638200024:root
              - arn:aws:iam::227793691312:root
              - arn:aws:iam::227011717743:root
              - arn:aws:iam::041821919363:root
              - arn:aws:iam::639676961119:root
              - arn:aws:iam::938727733271:root
              - arn:aws:iam::796796542496:root
              - arn:aws:iam::215308655391:root
              - arn:aws:iam::720557144887:root
              - arn:aws:iam::859416391807:root
              - arn:aws:iam::512481679155:root
              - arn:aws:iam::339153151760:root
              - arn:aws:iam::020959639949:root
              - arn:aws:iam::902577807644:root
              - arn:aws:iam::068039548225:root
              - arn:aws:iam::002827315474:root
              - arn:aws:iam::188129649881:root
              - arn:aws:iam::035781065801:root
              - arn:aws:iam::060998627520:root
              - arn:aws:iam::121922704398:root
              - arn:aws:iam::590119761358:root
              - arn:aws:iam::756241440375:root
              - arn:aws:iam::831628682309:root
              - arn:aws:iam::873302766205:root
              - arn:aws:iam::319044514607:root
              - arn:aws:iam::387576552623:root
              - arn:aws:iam::944106961327:root
              - arn:aws:iam::091089235314:root
              - arn:aws:iam::726805105719:root
              - arn:aws:iam::978261374777:root
              - arn:aws:iam::872722267528:root
              - arn:aws:iam::003998443196:root
              - arn:aws:iam::649044511533:root
              - arn:aws:iam::994075455914:root
              - arn:aws:iam::858664478982:root
              - arn:aws:iam::980851882997:root
              - arn:aws:iam::438164225206:root
              - arn:aws:iam::303824459716:root
          Action: s3:*
          Resource:
            - !Sub arn:aws:s3:::${pS3BucketName}
            - !Sub arn:aws:s3:::${pS3BucketName}/*
